contatos/urls.py
from django.urls import path
from contatos.views import index,ver_contato,busca,categoria

urlpatterns = [
    path('',index,name='index'),
    path('busca/',busca,name='busca'),
    path('busca/<str:categoria_name>',categoria,name='categoria'),
    path('contatos/<str:contato_id>',ver_contato,name='ver_contato'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('contatos.urls')),
    path('',include('usuarios.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contatos/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth import get_user_model
class Contatos(models.Model):
    CATEGORIA_BASE = (
        ('F','Familia'),
        ('A','Amigo'),
        ('S','Serviço'),
        ('R','Represetantes')
    )
    
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, null=False, blank=False)
    sobrenome = models.CharField(max_length=50, null=False, blank=False)
    telefone = models.CharField(max_length=15, null=False,blank=False)
    email = models.EmailField(max_length=100, null=False, blank=True)
    data_criacao = models.DateTimeField(default=datetime.now, null=False, blank=False)
    categoria = models.CharField(max_length=1, choices=CATEGORIA_BASE, default='', null=False, blank=False)
    descriçao = models.TextField(max_length=300, null=False, blank=True)
    foto = models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')
    mostrar = models.BooleanField(default=True)

    def __str__(self):
        return self.nome

contatos/views.py
from django.shortcuts import render,get_object_or_404,redirect
from contatos.models import Contatos
from django.core.paginator import Paginator
from django.http import Http404
from django.db.models import Q,Value
from django.db.models.functions import Concat
from django.contrib import messages
from django.contrib.auth.models import User

def index(request):
    if request.user.is_authenticated: 
        contatos = Contatos.objects .order_by('-id').filter(mostrar=True,user=request.user.id)
    else:
        contatos = Contatos.objects .order_by('-id').filter(mostrar=False)
    paginator = Paginator(contatos,10)
    page = request.GET.get('page')
    contatos = paginator.get_page(page)

    return render(request,'home/index.html',{'contatos':contatos})

def ver_contato(request,contato_id):
    contato = get_object_or_404(Contatos,id=contato_id)
    if not contato.mostrar:
        raise Http404()
    return render(request,'contato/detalhes.html',{'contato':contato})

def busca(request):
    termo = request.GET.get('termo')
    
    if termo is None or not termo:
        messages.error(request,'Campo de busca nao pode fica vazio ')
        return redirect('index')

    campos = Concat('nome',Value(' '),'sobrenome')
    if request.user.is_authenticated:
        contatos = Contatos.objects.annotate(
            nome_completo=campos
        ).filter(mostrar=True,user=request.user.id,nome_completo__icontains=termo
        )
    else:
        contatos = Contatos.objects.annotate(
        nome_completo=campos
        ).filter(mostrar=False,nome_completo__icontains=termo
        )
    paginator = Paginator(contatos,5)
    page = request.GET.get('page')
    contatos = paginator.get_page(page)

    return render(request,'home/busca.html',{'contatos':contatos})

def categoria(request,categoria_name):
    if request.user.is_authenticated:
        contatos = Contatos.objects.order_by('-id').filter(mostrar=True,user=request.user.id,categoria=categoria_name)
    else:
        contatos = Contatos.objects.order_by('-id').filter(mostrar=False,categoria=categoria_name)
    print(contatos)
    paginator = Paginator(contatos,10)
    page = request.GET.get('page')
    contatos = paginator.get_page(page)
    return render(request,'home/busca.html',{'contatos':contatos})

templates/contato/detalhes.html
{% extends 'base/base.html' %}
{% block title %}{{contato.nome}} | {% endblock %}
{% block base%}

<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      {% include 'partials/_busca.html' %}
      {% if contato %}
      <h1 class="mt-5">{{contato.nome.capitalize}} {{contato.sobrenome.capitalize}}</h1>
      {% if contato.foto %}
      <img src="{{contato.foto.url}}" style="max-width: 250px; heigth: auto;" alt=""> 
      {%else%}
      {%endif%}

      <dl>
        <dt>Telefone</dt>
        <dd>{{contato.telefone}}</dd>
        <p></p>
        <dt>E-mail</dt>
        {% if not contato.email %}
        Sem informaçoes!!
        {%else%}
        <dd>{{contato.email}}</dd>
        {%endif%}
        <p></p>
        <dt>Data criação</dt>
        <dd>{{contato.data_criacao}}</dd>
        <p></p>
        <dt>Categoria</dt>
        <dd>{{contato.get_categoria_display}}</dd>
        <p></p>
        <dt>Descrição</dt>
        {% if not contato.descriçao %}
        <dd>
          Sem informaçoes!!
        </dd>
        {%else%}
        <dd>
          {{contato.descriçao}}
        </dd>
        {%endif%}
      </dl>

    </div>
  </div>
</div>

{%endif%}
{% endblock%}